M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon May 18 11:15:08 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-18T11:15:08+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C320.000
%
G90
G05
T1
X300.0Y-300.0
X300.0Y-3700.0
X5700.0Y-300.0
X5700.0Y-3700.0
M30
